// ============================================================================
//  RAMstain - Legal documents (Disclaimer, Privacy Policy, Terms of Use)
//
//  Stored as UTF-8 string literals and converted to wide text in the UI
//  (see OnLegalDoc -> Utf8ToWide). These are plain-language templates written
//  to match the tool's actual behavior (offline, no data transmission, no
//  accounts). Review with a qualified lawyer before public distribution.
// ============================================================================
#pragma once

static const char* kLegalDisclaimer =
"DISCLAIMER\n"
"============\n"
"\n"
"RAMstain is an experimental, offline physical-memory capture utility "
"provided \"as is\", for forensic and incident-response use by qualified "
"professionals.\n"
"\n"
"1. Forensic suitability. Memory images produced by RAMstain are raw, "
"page-aligned physical memory captures (4 KiB). They are not analyzed, "
"parsed, or enriched by this tool, and may not be directly loadable by "
"every forensic product. You are responsible for validating that captured "
"images meet the evidentiary and chain-of-custody requirements of your "
"jurisdiction and organization. RAMstain writes an MD5 digest and a "
"metadata sidecar (.meta) to support integrity verification, but it is "
"your responsibility to maintain a proper chain of custody.\n"
"\n"
"2. Accuracy and completeness. Physical memory contents change constantly. "
"A capture is a point-in-time snapshot and is inherently non-repeatable. "
"RAMstain makes no guarantee that a capture is complete, consistent, or "
"forensically admissible in any given context. Some system or virtualized "
"configurations (e.g. newer Windows builds with hardened kernels, VM "
"guests, protected memory, or security software) may prevent full "
"physical-memory access; in those cases the tool reports the failure and "
"does not produce an image.\n"
"\n"
"3. No warranty. To the maximum extent permitted by law, the author "
"disclaims all warranties, express or implied, including merchantability, "
"fitness for a particular purpose, and non-infringement. The author shall "
"not be liable for any direct, indirect, incidental, consequential, or "
"special damages arising from the use of, or inability to use, RAMstain, "
"including loss of evidence, data, or business opportunity.\n"
"\n"
"4. Authorized use only. You are solely responsible for ensuring you have "
"legal authority to capture memory from the machine you are using. "
"Capturing memory without proper authorization may be unlawful.\n"
"\n"
"By using RAMstain you acknowledge and accept this disclaimer.";

static const char* kLegalPrivacy =
"PRIVACY POLICY\n"
"===============\n"
"\n"
"RAMstain is an offline tool. It has no accounts, no online service, and "
"no telemetry. This policy describes exactly what data it handles and what "
"it does not collect.\n"
"\n"
"1. No data collection. RAMstain does not collect, transmit, store, or "
"report any personal data, usage data, device identifiers, or diagnostic "
"information to anyone. It makes no network connections of any kind. The "
"only data it ever writes is the memory image you explicitly choose to "
"save, and its accompanying .meta metadata sidecar.\n"
"\n"
"2. Local files only. The image (.raw) and metadata (.meta) files you "
"create are written only to the location you specify. They contain "
"potentially sensitive information (anything that was in physical memory "
"at capture time). You are solely responsible for how those files are "
"stored, encrypted, transferred, and disposed of.\n"
"\n"
"3. Metadata captured. The .meta sidecar records, locally, the image path, "
"computer name, OS version and build, kernel version, capture timestamp, "
"image size, page count, and MD5 digest. This is written to the file you "
"choose, not sent anywhere.\n"
"\n"
"4. No third parties. RAMstain does not embed third-party services, "
"analytics, or advertising components, and it does not download updates or "
"content at runtime. It does bundle one third-party program, the WinPmem "
"memory imager (Apache License 2.0), which runs locally only and makes no "
"network connections.\n"
"\n"
"5. Security of your images. Because a memory image can contain credentials, "
"keys, and personal information, treat every file it produces as highly "
"sensitive. Encrypt at rest, limit access, and securely destroy images when "
"they are no longer needed.\n"
"\n"
"6. Children's privacy. RAMstain is a professional tool not directed at "
"children. No personal data is collected, so no children's data is "
"processed.\n"
"\n"
"In short: RAMstain collects nothing and transmits nothing. The only "
"confidential data involved is the memory image you create, which you "
"control entirely.";

static const char* kLegalTerms =
"TERMS OF USE\n"
"============\n"
"\n"
"1. Grant of license. Subject to these terms, the author grants you a "
"limited, non-exclusive, non-transferable, revocable license to use "
"RAMstain on systems you own or are authorized to access, for lawful "
"forensic, incident-response, and testing purposes.\n"
"\n"
"2. Acceptance. By running RAMstain you agree to these Terms of Use and "
"the accompanying Disclaimer. If you do not agree, do not use the tool.\n"
"\n"
"3. Authorized use only. You may only use RAMstain on machines for which "
"you have explicit legal authority to capture memory (ownership, written "
"consent, or legal process). You are solely responsible for complying with "
"applicable laws, regulations, and organizational policies.\n"
"\n"
"4. Prohibited uses. You may not use RAMstain to: (a) capture memory you "
"are not authorized to access; (b) infringe any intellectual-property, "
"privacy, or data-protection rights; or (c) commit any unlawful act. The "
"author disclaims responsibility for any misuse.\n"
"\n"
"5. No modification or redistribution. You may not modify, reverse-engineer, "
"sub-license, or redistribute RAMstain or any portion of it without prior "
"written permission, except as required by applicable law. This section does "
"not restrict the third-party software listed under \"Third-party software\" "
"below, which is licensed under its own terms.\n"
"\n"
"6. Intellectually property. RAMstain, including its code, design, name, and "
"trademarks, remains the property of the author. Nothing in these terms "
"transfers ownership.\n"
"\n"
"7. Termination. This license is automatically terminated if you violate "
"these terms. Upon termination you must cease use and destroy all copies "
"you control.\n"
"\n"
"8. Disclaimer and limitation of liability. RAMstain is provided \"as is\" "
"without warranty of any kind. To the maximum extent permitted by law, the "
"author is not liable for any damages arising from your use of RAMstain. "
"See the Disclaimer for details.\n"
"\n"
"9. Changes. The author may update these terms. Continued use after changes "
"constitutes acceptance.\n"
"\n"
"These terms are a plain-language template and should be reviewed by a "
"qualified lawyer in your jurisdiction before public distribution.";
