// ============================================================================
//  RAMstain - Legal documents (Disclaimer, Privacy Policy, Terms of Use)
//
//  Stored as UTF-8 string literals and converted to wide text in the UI
//  (see OnLegalDoc -> Utf8ToWide). These are plain-language templates written
//  to match the tool's actual behavior (offline, no data transmission, no
//  accounts). Review with a qualified lawyer before public distribution.
// ============================================================================
#pragma once

static const char* kLegalDisclaimer =
"DISCLAIMER\n"
"============\n"
"\n"
"RAMstain is an experimental, offline physical-memory capture utility "
"provided \"as is\", for forensic and incident-response use by qualified "
"professionals.\n"
"\n"
"1. Forensic suitability. Memory images produced by RAMstain are raw, "
"page-aligned physical memory captures (4 KiB). They are not analyzed, "
"parsed, or enriched by this tool, and may not be directly loadable by "
"every forensic product. You are responsible for validating that captured "
"images meet the evidentiary and chain-of-custody requirements of your "
"jurisdiction and organization. RAMstain writes a SHA-256 digest and a "
"metadata sidecar (.meta) to support integrity verification, but it is "
"your responsibility to maintain a proper chain of custody.\n"
"\n"
"2. Accuracy and completeness. Physical memory contents change constantly. "
"A capture is a point-in-time snapshot and is inherently non-repeatable. "
"RAMstain makes no guarantee that a capture is complete, consistent, or "
"forensically admissible in any given context. Some system or virtualized "
"configurations (e.g. newer Windows builds with hardened kernels, VM "
"guests, protected memory, or security software) may prevent full "
"physical-memory access; in those cases the tool reports the failure and "
"does not produce an image.\n"
"\n"
"3. No warranty. To the maximum extent permitted by law, the authors "
"disclaims all warranties, express or implied, including merchantability, "
"fitness for a particular purpose, and non-infringement. The authors shall "
"not be liable for any direct, indirect, incidental, consequential, or "
"special damages arising from the use of, or inability to use, RAMstain, "
"including loss of evidence, data, or business opportunity.\n"
"\n"
"4. Authorized use only. You are solely responsible for ensuring you have "
"legal authority to capture memory from the machine you are using. "
"Capturing memory without proper authorization may be unlawful.\n"
"\n"
"By using RAMstain you acknowledge and accept this disclaimer.";

static const char* kLegalPrivacy =
"PRIVACY POLICY\n"
"===============\n"
"\n"
"RAMstain is an offline tool. It has no accounts, no online service, and "
"no telemetry. This policy describes exactly what data it handles and what "
"it does not collect.\n"
"\n"
"1. No data collection. RAMstain does not collect, transmit, store, or "
"report any personal data, usage data, device identifiers, or diagnostic "
"information to anyone. It makes no network connections of any kind. The "
"only data it ever writes is the memory image you explicitly choose to "
"save, and its accompanying .meta metadata sidecar.\n"
"\n"
"2. Local files only. The image (.raw) and metadata (.meta) files you "
"create are written only to the location you specify. They contain "
"potentially sensitive information (anything that was in physical memory "
"at capture time). You are solely responsible for how those files are "
"stored, encrypted, transferred, and disposed of.\n"
"\n"
"3. Metadata captured. The .meta sidecar records, locally, the image path, "
"computer name, OS version and build, kernel version, capture start and "
"finish times (UTC and local), "
"image size, page count, SHA-256 digest, and any case number, examiner name "
"and notes you enter. A run log (.log) next to it records the same details, "
"your Windows user name and the command line, and each step of the run. "
"These are written to the folder you choose, not sent anywhere.\n"
"\n"
"4. No third parties. RAMstain does not embed third-party services, "
"analytics, or advertising components, and it does not download updates or "
"content at runtime. It does bundle one third-party program, the WinPmem "
"memory imager (Apache License 2.0), which runs locally only and makes no "
"network connections.\n"
"\n"
"5. Security of your images. Because a memory image can contain credentials, "
"keys, and personal information, treat every file it produces as highly "
"sensitive. Encrypt at rest, limit access, and securely destroy images when "
"they are no longer needed.\n"
"\n"
"6. Children's privacy. RAMstain is a professional tool not directed at "
"children. No personal data is collected, so no children's data is "
"processed.\n"
"\n"
"In short: RAMstain collects nothing and transmits nothing. The only "
"confidential data involved is the memory image you create, which you "
"control entirely.";

static const char* kLegalTerms =
"TERMS OF USE\n"
"============\n"
"\n"
"1. License. RAMstain is open-source software released under the MIT "
"License (see the LICENSE file that accompanies the source code). You may "
"use, copy, modify, and distribute it under those terms. The MIT License "
"governs the software itself; these terms only describe how the tool may be "
"used.\n"
"\n"
"2. Authorized use only. Use RAMstain only on machines you own or for which "
"you have explicit legal authority to capture memory (ownership, written "
"consent, or legal process). You are solely responsible for complying with "
"applicable laws, regulations, and organizational policies.\n"
"\n"
"3. Prohibited uses. Do not use RAMstain to capture memory you are not "
"authorized to access, to infringe privacy or data-protection rights, or "
"for any other unlawful purpose.\n"
"\n"
"4. Sensitive output. Memory images can contain passwords, keys, and "
"personal data. You are responsible for how the images you create are "
"stored, protected, transferred, and disposed of.\n"
"\n"
"5. No warranty. RAMstain is provided \"as is\", without warranty of any "
"kind, as stated in the MIT License. To the maximum extent permitted by law, "
"the authors are not liable for any damages arising from its use. See the "
"Disclaimer for details.\n"
"\n"
"6. Copyright. Copyright (c) 2026 RAMstain contributors.\n"
"\n"
"These terms are a plain-language summary and should be reviewed by a "
"qualified lawyer in your jurisdiction before public distribution.";
